### ISSUE TITLE
scrollToChannel and scrollToScene broken

### ISSUE THREAD

**Issue by fappaas** [teotigraphix/Framework4Bitwig#103] opened 2015-11-27 15:46 UTC
scrollToChannel and scrollToScene must be called twice to work reliably.

See the scrollToChannel and scrollToScene functions in AbstractTrackBankProxy.js of Framework4Bitwig.

**Comment by git-moss** [comment] 2016-03-05 15:09
This is not a bug. This function makes the track visible on the controller NOT in the Bitwig UI.

However by testing this I found a more weird bug:

If you create a 8 track bank, position the bank > track 16 (3rd page) and then try to move to the 1st bank (e.g. scrollToChannel 0) the 2nd page is selected.

You can test that with Push4Bitwig if you enter in the console:
controller.model.trackBank.trackBank.scrollToChannel (20)
-> works fine
controller.model.trackBank.trackBank.scrollToChannel (0)
-> Jumps to 2nd page

It works fine if you are on the 2nd page and then jump to the 1st.

**Comment by git-moss** [comment] 2017-01-21 15:12
Still in 1.3.15 and Alpha 7.

**Comment by git-moss** [comment] 2017-02-18 12:29
Test with Push4Bitwig: Start with the default project and keep adding track by pressing "Add Track", which uses the function to  select the newly created track.

**Comment by git-moss** [comment] 2017-11-04 08:53
Fixed by switching to:
trackBank.sceneBank ().scrollPosition ().set (position)

**Closed by git-moss** 2017-11-04 08:53 UTC
Labels: 1.3.x, 2.0, bitwig-bug, category-tracks, important
